In [1]:
import pyneb as pn
import numpy as np
import matplotlib.pyplot as plt

In [2]:
rc = pn.RedCorr()
wl = [4861, 6000, 3000]

In [3]:
rc.getLaws()

['G03 LMC',
 'K76',
 'F99-like',
 'F88 F99 LMC',
 'No correction',
 'SM79 Gal',
 'MCC99 FM90 LMC',
 'CCM89 Bal07',
 'CCM89 oD94',
 'S79 H83 CCM89',
 'F99',
 'CCM89']

In [4]:
rc.law = 'CCM89'
rc.cHbeta = 1.5
print rc.AV, rc.E_BV

3.22120161009 1.03909729358


In [5]:
rc.getCorr(wl)

array([  31.63257384,   14.73273503,  220.1201056 ])

In [6]:
rc.getCorrHb(wl)

array([ 1.00030982,  0.46588999,  6.96080892])

In [7]:
rc.law = 'F99'

In [8]:
rc.getCorr(wl)

array([  31.63283197,   13.03554862,  206.35727716])

In [9]:
rc2 = pn.RedCorr(law='F99')
rc2.cHbeta = 1.5
print rc2.getCorrHb(wl)
print rc2.getCorr(wl)

[ 1.00031798  0.41222024  6.52559008]
[  31.63283197   13.03554862  206.35727716]


In [10]:
rc2 = pn.RedCorr(law='S79 H83 CCM89')
rc2.cHbeta = 1.5
print rc2.getCorrHb(wl)
print rc2.getCorr(wl)

[ 1.00028166  0.44445142  5.86503785]
[  31.63168359   14.05478793  185.46878163]


In [11]:
rc2 = pn.RedCorr(law='SM79 Gal')
rc2.cHbeta = 1.5
print rc2.getCorrHb(wl)
print rc2.getCorr(wl)

[ 1.00029706  0.45216383  6.82617585]
[  31.63217059   14.29867585  215.86263397]


In [12]:
rc2 = pn.RedCorr(law='K76')
rc2.cHbeta = 1.5
print rc2.getCorrHb(wl)
print rc2.getCorr(wl)

[ 1.00027724  0.43955201  5.82116986]
[ 1.00025358  0.43954162  5.82103218]


In [13]:
rc2.cHbeta = 1.5
print rc2.getCorrHb(wl)
print rc2.getCorr(wl)

[ 1.00027724  0.43955201  5.82116986]
[ 1.00025358  0.43954162  5.82103218]


In [16]:
rc2 = pn.RedCorr()
rc2.cHbeta = 3
print(rc2.AV, rc2.E_BV, rc2.cHbeta)
rc2.law = 'K76'
print(rc2.AV, rc2.E_BV, rc2.cHbeta)
rc2.cHbeta = 3
print(rc2.AV, rc2.E_BV, rc2.cHbeta)
rc2.cHbeta = 3
print(rc2.AV, rc2.E_BV, rc2.cHbeta)
rc2.E_BV = 3
print(rc2.AV, rc2.E_BV, rc2.cHbeta)
rc2.E_BV = 3
print(rc2.AV, rc2.E_BV, rc2.cHbeta)
rc2.AV = 3
print(rc2.AV, rc2.E_BV, rc2.cHbeta)
rc2.AV = 3
print(rc2.AV, rc2.E_BV, rc2.cHbeta)
rc2.cHbeta = 3
print(rc2.AV, rc2.E_BV, rc2.cHbeta)


(0.0, array(0), array(3))
(array([ 23.25]), array([ 7.5]), array(3))
(-3395228.5736711812, -1095235.0237648971, array(3))
(495809766342.93518, 159938634304.17264, array(3))
(9.3000000000000007, array(3), -2.0543535872926802e-05)
(9.3000000000000007, array(3), 1.4067895538741014e-10)
(array(3), 0.96774193548387089, -9.6334772218904304e-16)
(array(3), 0.96774193548387089, 6.5968561629643084e-21)
(-438094.00950595882, -141320.64822772864, array(3))
